### ISSUE TITLE
not sure this is related to bookmark. why is it here? what's the usage?

### ISSUE THREAD

**Issue by kirshamir** [shahartal81/BIQ2PassoverProject#16]
https://github.com/shahartal81/BIQ2PassoverProject/blob/e6bd6e13ed0c5d8ac66aa36a6b6c91aa8968cba1/src/main/java/additionalclasses/Bookmark.java#L12

**Comment by shahartal81** [comment]
The usage for that is when we save a bookmark, we save which moves we did when we set this bookmark.
For example, we created a bookmark and then we turned left, then we save on the bookmark the LEFT move so if we get to this bookmark again, we don't want to do LEFT again, but to turn to a different direction.
