### ISSUE TITLE
I'm note sure I understand this test (or maybe it is too naive) - ?

### ISSUE THREAD

**Issue by kirshamir** [shahartal81/BIQ2PassoverProject#2]
https://github.com/shahartal81/BIQ2PassoverProject/blob/e6bd6e13ed0c5d8ac66aa36a6b6c91aa8968cba1/test/main/java/player/PlayerFactoryTest.java#L53

**Comment by shahartal81** [comment]
This is the naive test, wasn't sure if really needed or not, can be removed
