### ISSUE TITLE
in glue don't use @And (even though it compiles) - stick to: Given, When, Then to convey the actual purpose of this step

### ISSUE THREAD

**Issue by kirshamir** [shahartal81/BIQ2PassoverProject#3]
https://github.com/shahartal81/BIQ2PassoverProject/blob/e6bd6e13ed0c5d8ac66aa36a6b6c91aa8968cba1/test/main/java/player/PlayerBookMarkEachStep/PlayerBookmarkEachStepStepdefs.java#L37

**Comment by shahartal81** [comment]
Replaced And with When and Then in the new branch
