### ISSUE TITLE
can be combined with the previous step "we do a move" - ?

### ISSUE THREAD

**Issue by kirshamir** [shahartal81/BIQ2PassoverProject#4]
https://github.com/shahartal81/BIQ2PassoverProject/blob/e6bd6e13ed0c5d8ac66aa36a6b6c91aa8968cba1/test/main/java/player/PlayerBookMarkEachStep/PlayerBookmarkEachStepStepdefs.java#L27

**Comment by shahartal81** [comment]
This one is not saving the result in the "move" member, and the other one is.
I didn't see any other way to do it in order to not override the "move" member...
