### ISSUE TITLE
how do you hit a bookmark if you haven't set one before in previous steps?

### ISSUE THREAD

**Issue by kirshamir** [shahartal81/BIQ2PassoverProject#5]
https://github.com/shahartal81/BIQ2PassoverProject/blob/e6bd6e13ed0c5d8ac66aa36a6b6c91aa8968cba1/test/main/java/player/PlayerBookMarkEachStep/PlayerBookmarkEachStep.feature#L32

**Comment by shahartal81** [comment]
The algorithm of PlayerBookmarkEachStep sets bookmark 0 and then puts also bookmark when it hits a wall, so that's how we get to bookmark with sequence 1
