### ISSUE TITLE
why here: 1 and 2 and above: 0 and 1

### ISSUE THREAD

**Issue by kirshamir** [shahartal81/BIQ2PassoverProject#6]
https://github.com/shahartal81/BIQ2PassoverProject/blob/e6bd6e13ed0c5d8ac66aa36a6b6c91aa8968cba1/test/main/java/player/PlayerBookMarkEachStep/PlayerBookmarkEachStep.feature#L41

**Comment by shahartal81** [comment]
Here we set a bookmark 0 when we start, then we hit wall and then we set bookmark with sequence 1.
In the above test, we check that we indeed set bookmark 0 when we just started.
