### ISSUE TITLE
how can you know that this is the problem?

### ISSUE THREAD

**Issue by kirshamir** [shahartal81/BIQ2PassoverProject#9]
https://github.com/shahartal81/BIQ2PassoverProject/blob/e6bd6e13ed0c5d8ac66aa36a6b6c91aa8968cba1/src/main/java/gamemanager/GameManager.java#L65

**Comment by yl0871** [comment]
Fixed - it was an initial error message(the context was out of bounds of the Enum options, not the map).
Changed the error message
